### ISSUE TITLE
No routing on local dev server

### ISSUE THREAD

**Issue by PARC6502** [Chronoblog/gatsby-theme-chronoblog#17]
Heya, I'm having an issue where routing isn't working on the dev server launched by `gatsby develop`.

## Recreating the behaviour

1. Create a fresh starter 
2. Navigate to `localhost:8000` and click on on the full blog post example
3. Result is that the page navigates to `http://full-blog-post/`
4. Try navigating to `http://localhost:8000/full-blog-post` --> you get a blank page

Once published online the routing works normally.

**Comment by PARC6502** [comment]
Actually, I am now even having the issue with the published site, here is an example: 

https://personal-chronoblog.now.sh/

**Comment by Ganevru** [comment]
Hi. It’s hard to say what’s wrong. Maybe something in the gatsby-config.js file? What do you have in siteUrl and pathPrefix?

Do you work for windows? As far as I know, there are problems when working with gatsby. To be honest, it's hard for me to say something about how to fix problems associated with development on Windows.

**Comment by PARC6502** [comment]
Do you have any idea why it might work on the now deployment?

This is currently what my siteUrl and pathPrefix look like:

```json
    siteUrl: 'https://ibby.blog/',
    pathPrefix: '/',
```

**Comment by Ganevru** [comment]
Try to use exactly the URL on which site is placed in siteUrl. That is, for https://personal-chronoblog.now.sh - write it like this: 

`siteUrl: 'https://personal-chronoblog.now.sh/',`

**Comment by PARC6502** [comment]
Hi, regarding the dev server, you were right about it being a windows issue.

I set up a linux environment and it works well.

**Comment by Ganevru** [comment]
I guess it can be closed
