### ISSUE TITLE
Add fallback for backdrop-filter on cover image

### ISSUE THREAD

**Issue by PARC6502** [Chronoblog/gatsby-theme-chronoblog#18]
By default backdrop-filter is disabled on Firefox and needs to be enabled manually through a flag.

So that the website remains aesthetic on firefox, I think it would be best to add a fallback for the backdrop-filter that works on Firefox.  

Perhaps something like this:
```javascript
<Image
    css={`
    @supports (backdrop-filter: blur(5px)) {
        background-color: rgba(255,255,255,0);
    }
    background-color: rgba(255,255,255,0.6);
    `}
    sx={{
    backdropFilter: 'blur(5px) contrast(50%)',
    WebkitBackdropFilter: 'blur(5px) contrast(50%)',
    maxHeight: height,
    minHeight: height,
    borderRadius: 'card',
    ...borderRadiusForCard
    }}
    imgStyle={{
    objectFit,
    objectPosition: '50% 50%'
    }}
    alt={imageTitle}
    title={imageTitle}
    fluid={coverFluidImage}
/>
```
There is probably a better way to recreate the blur, I'm using something similar to this (with the colour of the transparent background matching my primary colour) as a stop gap in the meantime.

**Comment by Ganevru** [comment]
You have a great solution! But, I think it's better to use a more neutral gray color, something like this:

```jsx
css={`
  @supports (backdrop-filter: blur(5px)) {
    background-color: rgba(255, 255, 255, 0);
  }
  background-color: rgba(40, 40, 40, 0.7);
`}
```

Color `rgba (255,255,255,0.6)` is too light for a dark theme. And I don’t want to make different options for different color themes.

@PARC6502, create a pull request.

**Comment by Ganevru** [comment]
Added https://github.com/Chronoblog/gatsby-theme-chronoblog/commit/22462a664fca0a57f0128d032b7b2ee4e97d283b
