### ISSUE TITLE
URL path for "full-blog-post" getting built incorrectly?

### ISSUE THREAD

**Issue by reallymello** [Chronoblog/gatsby-theme-chronoblog#22]
New to gatsby, created a site with this fantastic starter blog, and it appears to work with the exception of the "full-blog-post" example. The link goes to http://full-blog-post/ so it is a broken link.

Inspecting the dom it looks like
`<a class="hover-on css-wioi95" href="/\full-blog-post\">`

What could be wrong if the paths aren't building out correctly?

**Comment by Ganevru** [comment]
Hey. I guess this is the same problem that was described here: https://github.com/Chronoblog/gatsby-theme-chronoblog/issues/17

Do you use windows for development?

**Comment by reallymello** [comment]
I do. Known issue or?

**Comment by Ganevru** [comment]
To be honest, I don’t know exactly what the problem is, maybe this is some very simple bug 😕

In general, Windows now has the ability to use Linux for development: https://docs.microsoft.com/en-us/windows/wsl/about

**Comment by Ganevru** [comment]
It was so stupid of me 😅 For some reason, I used `path.join('/', slug);` for forming links, but this function is specially made to create different paths in different systems.

I think I will release an update soon.

**Comment by Ganevru** [comment]
version 0.15.0 should fix this

**Comment by reallymello** [comment]
Confirmed, tried 0.15.0 this morning. I was able to build on my Windows environment now without the path issue. Thank you so much!
