### ISSUE TITLE
Multi-colored tags

### ISSUE THREAD

**Issue by jamstack-elise** [Chronoblog/gatsby-theme-chronoblog#26]
💡 **UI-Idea:** 
1. Format current Theme-UI component Button/Badge similar to the appearance of preformatted text tags 
2. Assign each tag a color

🎯 **Goal**
Viewers of the profile can easily identify tags by way of color and formatting.

📋 **Initial steps to solve the problem**
(for 1)
* Get familiar with tag component codebase at filepath: 
`gatsby-theme-chronoblog/packages/gatsby-theme-chronoblog/src/components/tags/tags.js`
* Test new variant attributes for Theme-UI Badge component [https://theme-ui.com/components/badge](url)
* Creative inspo for UI tag patterns via examples [http://ui-patterns.com/patterns/Tag](url)

(for 2)
TBD

**End goal:** Celebrate🎉!

**Comment by Ganevru** [comment]
Thanks for the idea! I close this issue in favor of this https://github.com/Chronoblog/gatsby-theme-chronoblog/issues/33

I believe the implementation of global tag management will solve this question too.
