### ISSUE TITLE
FontAwesome solid icons

### ISSUE THREAD

**Issue by jamstack-elise** [Chronoblog/gatsby-theme-chronoblog#29]
💡 UI-Idea: Include [FontAwesome's solid icon svgs](https://www.npmjs.com/package/@fortawesome/react-fontawesome) in the codebase library

🎯 Goal
Include the {faEnvelopeSquare} object for developer's who want to use an 'email' button
Or via array-- icon={['fas', icon]}

📋 Initial steps to solve the problem
- explore gatsby-theme-chronoblog/packages/src/components/social-links.js codebase
- test

End goal: the code works, and celebrate🎉!

**Comment by jamstack-elise** [comment]
tests:
- imported npm package for @fortawesome/free-solid-svg-icons, and imported {faEnvelopeSquare}
- added <FontAwesomeIcon icon='envelope-square' /> into line 32
- updated gatsby-config

results:
- url updates
- icon does not appear (see attached screenshot)

![image](https://user-images.githubusercontent.com/56519814/72659699-f748b580-3991-11ea-8eba-467132d733a7.png)

**Comment by Ganevru** [comment]
Yes, that's a good idea.

The user should be able to indicate their email like this (in gatsby-config.js):

```
{
  icon: `envelope`,
  url: `mailto:hello@mail.com`
},
```

I wrote this in a test starter (but it doesn't work yet, of course): https://github.com/Chronoblog/gatsby-theme-chronoblog/blob/master/starters/tests/gatsby-config.js

**Comment by Ganevru** [comment]
![Screen Shot 2020-04-16 at 00 55 14](https://user-images.githubusercontent.com/8168280/79485489-00dbcb00-801e-11ea-8e5b-08e4a2202db0.png)

So now we can use the "envelope", "at" and "phone" icons in the author banner (need gatsby-theme-chronoblog version 0.19.0 or higher).
