### ISSUE TITLE
Creating new site banner

### ISSUE THREAD

**Issue by fmeehan** [Chronoblog/gatsby-theme-chronoblog#34]
Hi all, 

Ivan, I really like chronoblog what a nice theme!

I have been trying to do something simple on the surface, to create a site banner very very similar to AuthorBanner, with 2 columns, with the avatar image, having different background colours. 

Tried to create a new banner,  fmBlogBanner by writing a new component alongside author-banner.js, and inserted it in index.mdx with `<fmBlogBanner />` statement, added `import fmBlogBanner from './fmBlogBanner'`; in root.js, that does not render anything at all. 

Am I missing something or is there and easier way to create a column box in an MDX document?

Thanks in advance, 

François

**Comment by Ganevru** [comment]
Hi. Thanks for the feedback.

Any component should begin with a capital letter. So it should look something like this: `<FmBlogBanner />`

**Comment by fmeehan** [comment]
Thanks for the quick response! 

All the Best!!
