### ISSUE TITLE
How can I override a component style (for example, the Tags componet)?

### ISSUE THREAD

**Issue by gughog** [Chronoblog/gatsby-theme-chronoblog#37]
Hello and thanks for the great work on this theme! I want to modify the "Tags" component, to add some custom styles (like a custom background or text color). How can I do that ? I'm new to the gatsby world, so any help will be great.

**Comment by Ganevru** [comment]
Hello.

As I understand, it's about something like this: https://github.com/Chronoblog/gatsby-theme-chronoblog/issues/33 ?
