### ISSUE TITLE
image is on top of each other

### ISSUE THREAD

**Issue by zhex900** [Chronoblog/gatsby-theme-chronoblog#38]
Hi, 

I noticed the post image is on top of each other.

![Screen Shot 2020-03-05 at 8 17 41 am](https://user-images.githubusercontent.com/5380757/75923736-ced13800-5eb9-11ea-9260-354740a1936e.png)

**Comment by Ganevru** [comment]
Hi. Yes this is a firefox issue: https://github.com/Chronoblog/gatsby-theme-chronoblog/issues/18
