### ISSUE TITLE
How can I disable/hide this footer section in a post?

### ISSUE THREAD

**Issue by 17-09** [Chronoblog/gatsby-theme-chronoblog#39]
![image](https://user-images.githubusercontent.com/49329758/78336338-67da9800-75b9-11ea-9726-88353fa239c9.png)

**Comment by 17-09** [comment]
Create a flag that indicates hide/show ContentBottomMdx?
![image](https://user-images.githubusercontent.com/49329758/78336707-05ce6280-75ba-11ea-95ce-57a8df52c741.png)

**Comment by Ganevru** [comment]
Hi!

If I understand correctly what you want to do, do this:

In `src/gatsby-theme-chronoblog/`

Create a file called `content-bottom.mdx`

Inside, fill it like this:

```md
<hr />
<FeedSearch />
<Tags />
<FeedItems />
```

And ... now you can add and remove anything from here. You can leave it empty and then there will be nothing, or add or remove something.

**Comment by 17-09** [comment]
Magic.
The building process will take my custom content-bottom.mdx instead of gatsby-theme-chronoblog 's content-bottom.mdx, right?

**Comment by Ganevru** [comment]
Yes, this is called "Shadowing", you can read more about it here: https://www.gatsbyjs.org/docs/themes/shadowing

**Comment by 17-09** [comment]
Let me try.
Thank you very much <3
