### ISSUE TITLE
Trouble updating banner.png

### ISSUE THREAD

**Issue by bkleeman** [Chronoblog/gatsby-theme-chronoblog#41]
Hi there,

I'm new to chronoblog and I love the work you're doing. Thank you for making such a great project available to us all!

I'm experiencing some difficulty updating my banner.png file. I am able to get the file to update locally, but the original starter banner.png appears when I try to link to my website on LinkedIn, Slack, etc. Can you help me determine if this is user error?

**More information**:

I have the file located at `static/banner.png`, and if I navigate to `<my_url>/banner.png`  in my browser, I can see the updated image. But when I try to link to it, I see this:

![image](https://user-images.githubusercontent.com/20052075/78726501-c4aabb00-78f7-11ea-8c69-828196366666.png)

This is the case across browsers, across apps, across devices.

I have checked to confirm that my latest deployment has the most recent build and confirmed that `banner.png` in my deployed codebase is the same file as I have locally. My website is hosted on GitHub pages if that makes any difference, but I have also tested this and found the same results with a dummy host through surge.sh.

Any advice on where I can poke around to solve this issue? Any other helpful info I can provide?

**Comment by Ganevru** [comment]
Hi! Thanks for the feedback 😊.

On your site, in meta information, banner.png is written like this:

`<meta data-react-helmet="true" name="image" content="https://bkleeman.surge.sh/banner.png">`

As I understand it, you also host your site on surge.sh, I suppose you have not changed the site address (`siteUrl`) in the `gatsby-config.js` file to `https://bkleeman.github.io/`.

**Comment by bkleeman** [comment]
That is super helpful, thank you for the info and the quick reply! You are right, looks like I forgot to change that when I pushed my site to production. I have updated my siteUrl now to point to the correct address.

Unfortunately though this doesn't seem to have fixed the issue. Or at least not yet? My GitHub Pages repo has the right siteUrl in the [JSON file](https://github.com/bkleeman/bkleeman.github.io/blob/master/static/d/3253928670.json) that the meta data is mapped out to and the head of the live site has indeed updated to show `<meta data-react-helmet="true" property="og:image" content="https://bkleeman.github.io/banner.png">`.  

![image](https://user-images.githubusercontent.com/20052075/78825185-25dc9800-79a5-11ea-8997-d4714723249d.png)

![image](https://user-images.githubusercontent.com/20052075/78825219-31c85a00-79a5-11ea-9122-c255f0f1d11b.png)



Any recommendations for further troubleshooting?

**Comment by Ganevru** [comment]
If the meta tags have the correct image, then everything is okay (maybe a third-party site somehow cached the old data?). 

You can check on the twitter validator: https://cards-dev.twitter.com/validator

**Comment by bkleeman** [comment]
Thank you for suggestion using a card validator! I tested the URL and it showed the correct image. I have it showing the right card when I try to link to my site now. I think you're right, the site I was posting to may have just been holding onto an old version in the cache. Thanks for helping me step through it! Closing the issue.
