### ISSUE TITLE
Make an easy way to access post data from post-footer.mdx

### ISSUE THREAD

**Issue by vforverdu** [Chronoblog/gatsby-theme-chronoblog#42]
I'm using Disqus to add comments on my blog posts, but I need a unique identifier that allows me to know to which post a comment belongs.

A simple way to achieve this is to use the post's title, but I'd have to add a PostComments component to each blog post with its title.

What I'd like to do is to use some kind of variable referencing the post's title inside the post footer like this:

```
// post-comments.mdx

import { DiscussionEmbed } from "disqus-react"

export const PostComments = (props) => {
  	const disqusConfig = {
  		shortname: 'your-short-name',
  		config: { 
			identifier: props.title, 
	  		title: props.title,
  		},
  	}
  	return (
		<DiscussionEmbed {...disqusConfig} />
	);
}
```

```
// post-footer.mdx

import { PostComments } from './post-comments.mdx';

<PostComments title={post.title} />
<AuthorBanner />
```

I want that post.title variable to be a reference on the current post title.

Is there a simple way to achieve this?

**Comment by Ganevru** [comment]
Hi. Thanks for the detailed explanation.

I'm not sure how best to insert Disqus comments into the Chronoblog, I think there are several options. It is necessary to experiment/try various options, after which I will answer here and, possibly, update the documentation.

**Comment by vforverdu** [comment]
Okey thanks :D

**Comment by Ganevru** [comment]
ok, so far, only such an idea comes to my mind, just use the usual web api, like:

```js
location.href
location.pathname
```

but I'm not sure if this is the best solution =/

**Comment by Ganevru** [comment]
So, now through props in post-footer.mdx you can get information about the site and the post.

Here is an example of how this applies to Disqus:

```mdx
import { Disqus } from 'gatsby-plugin-disqus';

<AuthorBanner></AuthorBanner>
<p>&nbsp;</p>
<Disqus
	config={{
		url: props.siteMetadata.siteUrl + props.postData.fields.slug,
		title: props.postData.frontmatter.title,
		id: props.postData.id
	}}
/>
```

But in general, this way you can refer from post-footer.mdx to any information about the post.

This can only be done in the latest version of Chronoblog (v0.18.0)

**Comment by Ganevru** [comment]
https://github.com/Chronoblog/gatsby-theme-chronoblog/commit/53009211323500633b38ee125535c8075ce542d5

**Comment by Ganevru** [comment]
I also created an example of how to use Chronoblog and Disqus: https://github.com/Chronoblog/gatsby-theme-chronoblog/tree/master/examples/chronoblog-disqus

Web: https://chronoblog-disqus.now.sh/small-blog-post/
