### ISSUE TITLE
Have You considered Adding a Version that Works with Netlify CMS ? 

### ISSUE THREAD

**Issue by gxwheel152** [Chronoblog/gatsby-theme-chronoblog#45]
Love many aspects of this starter and theme >>> was just curious if you'd considered adding a Version that Works with Netlify CMS ? 

If there's a better place to ask that question or start that discussion, just let me know. 
Cheers

**Comment by Ganevru** [comment]
Hi!

Chronoblog can work with Netlify CMS, here is an example of this: [https://github.com/Chronoblog/gatsby-starter-chronoblog-netlify-cms](https://github.com/Chronoblog/gatsby-starter-chronoblog-netlify-cms)

But I still have to explain in more detail how to do this ([https://github.com/Chronoblog/gatsby-theme-chronoblog/issues/15](https://github.com/Chronoblog/gatsby-theme-chronoblog/issues/15))

**Comment by gxwheel152** [comment]
Thanks
