### ISSUE TITLE
How do I add/edit the CSS?

### ISSUE THREAD

**Issue by cmarabate** [Chronoblog/gatsby-theme-chronoblog#48]
I love this site but it completely baffles me how any of it works. I can't find anywhere to simply add/edit the CSS of the site. Where the heck is it all coming from because it is nowhere to be found in the src folder like I am used to. There must be something I am missing, could somebody please point me in the right direction?

**Comment by Ganevru** [comment]
Hi!

The most proper way to manage styles described here: https://github.com/Chronoblog/gatsby-theme-chronoblog#style-settings

To manage styles we use the [theme-ui](https://theme-ui.com/) library.

**Comment by cmarabate** [comment]
Hmmm I did find that but that doesn't look like CSS to me. I did try adding my CSS inside the main curly brackets but it did not do anything.

I'm not aware of the theme-ui library is that what I need to add my own custom CSS to the site?

Is there not a way I can simply add a global stylesheet to the site which would be placed below all the other CSS of the site so I could overwrite the CSS of elements and add my own CSS when I need to?

**Comment by Ganevru** [comment]
Gatsby's themes are what you build your site on top of. Everything you can do with Gatsby, you can do in Chronoblog.

To add global css, do as described here: [Adding global styles without a layout component
](https://www.gatsbyjs.org/docs/global-css/#adding-global-styles-without-a-layout-component)

**Comment by cmarabate** [comment]
Cool, that looks more like what I need. I appreciate the quick responses!
