### ISSUE TITLE
Ability to select multiple tags at a time?

### ISSUE THREAD

**Issue by cmarabate** [Chronoblog/gatsby-theme-chronoblog#49]
Would it be possible to edit the tag filters on the home page so that you could select as many tags as you want? Therefore if I selected a few tags, it would filter the results to only show anything that has any of the selected tags?

I am imagining this to work as so...

When you click a tag, it changes the background color of the tag button like it currently does. But if you click another tag afterward, it would select that tag as well and obviously change the background color of it too. Instead of changing to that tag like it currently does.

Thanks!

**Comment by Ganevru** [comment]
Thanks for the idea.

In my opinion, tags should not have too much functionality on a personal site - it's still a personal site, not a catalog or an online store.

**Comment by cmarabate** [comment]
Sure thing.

I get that. This is the first starter I found that has close to the tag filter functionality I am looking for, so I am trying to adapt it to be a multi-purpose site I could use for multiple different kinds of sites.

If you know of a starter that has the functionality I am looking for I would greatly appreciate it if you shared it with me.

This is a little unrelated but I have been messing with the CSS for hours trying to get it to display 4 articles per row but I seem to be getting nowhere. It is not that I don't know how to accomplish this, I have done it on multiple sites before but this one is coded so differently than I am used to. I think part of the problem is how the posts seem to get separated by year, I found where to turn off yearSeparator in gatsby-config.js but that seemed to just remove the separator title that displays the year. They seem to still be getting separated into different divs. None of the divs have a class I can target easily and all the elements that do have classes seem to be getting generated automatically. So I have no idea how to add custom classes to the containers to make things easier on me.

I admit I am fairly new to Gatsby and I have never experienced a Gatsby site before that uses a theme and has so much done through node_modules like this one does. So I don't expect you to teach me how to do everything I need to learn to make this work. But I just wanted to bring it up in-case you could point me in the right direction or maybe give you an idea for another starter you could create that would work the way I wish this one did =). I do love how easy everything is to do with this starter if there wasn't so much I wanted to redevelop to make it more multi-purpose. If I just wanted to create a blog, it would be perfect as is.

I would appreciate any help you can give me or any other starters you can refer me to that do what I want. But I will close this issue and won't be upset if you don't reply to this comment.

**Comment by Ganevru** [comment]
About CSS and styles. In Chronoblog, I use a rather unusual approach to styles. There, in general, it is not assumed that someone will manage the styles using css. If you need to go so deep into managing styles (beyond what the style settings allow https://github.com/Chronoblog/gatsby-theme-chronoblog#style-settings), then maybe you need to make your website without use of third-party themes.

At the expense of tags and filters. In fact, in my implementation of tags and filters, Gatsby is not particularly important. Gatsby is a React, and if you need functionality with filters, tags, etc., it might be better to look for libraries and examples of implementation in the React ecosystem.

**Comment by cmarabate** [comment]
Thanks. I will look into that. I appreciate the help!
