### ISSUE TITLE
How can I add pagination?

### ISSUE THREAD

**Issue by deepakness** [Chronoblog/gatsby-theme-chronoblog#60]
I am using the theme Chronoblog to add "notes" only (not posts and links).

Currently, I have 17+ notes which all shows up on the same page, is there any way I can add pagination to this?

[This](https://notes.deepakness.com/) is my website.

Thank you.

**Comment by Ganevru** [comment]
To be honest, I don't think pagination is a good UI solution.

I am thinking of adding something like virtualization so that the feed of a site with large content would just continue to load (as, say, a tweeter does).

**Comment by deepakness** [comment]
I completely agree with that.

But, in my case, if I have 100s of notes showing on the same page the site will load slow, right?

In that case, the infinite scroll feature would be good.

Anyways, thanks a lot.
