### ISSUE TITLE
Remove related posts from any post

### ISSUE THREAD

**Issue by deepakness** [Chronoblog/gatsby-theme-chronoblog#61]
Is there any way I can remove the related posts that come under any specific post?

Right now, I am getting all the other previous posts under [this post](https://notes.deepakness.com/loss-aversion/) and that will not be good if I have a lot of notes.

Thank you.

**Comment by Ganevru** [comment]
At your site, here: `src/gatsby-theme-chronoblog` - most likely there are files with names like `post-footer.mdx`, `site-footer.mdx` , and `site-header.mdx` (like this: https://github.com/Chronoblog/gatsby-starter-chronoblog/tree/master/src/gatsby-theme-chronoblog)

There you need to create another file, and name it: `content-bottom.mdx`

Inside the file, fill it like this: 

```
<hr />
```

Thus, you will replace the default value of this file, which looks like this: https://github.com/Chronoblog/gatsby-theme-chronoblog/blob/master/packages/gatsby-theme-chronoblog/src/content-bottom.mdx

**Comment by deepakness** [comment]
Yes, it works perfectly.

Thanks a lot, Ganevru.
