### ISSUE TITLE
Upgrade gatsby version with related dependencies

### ISSUE THREAD

**Issue by G-khan** [Chronoblog/gatsby-theme-chronoblog#72]
Is it possible to upgrade gatsbyjs version to **`v5`** with related dependencies? I tried that a few times but didn't have deep knowledge about it. Really appreciate it if there is a way to do it.

Related documents:
- https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/
- https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v3-to-v4/
- https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/

**Comment by ganevdev** [comment]
That would require a lot of effort. To be honest, I think it's even easier to create a Chronoblog analog/clone from scratch using the latest version of Gatsby, instead of making such changes to the current code base.
